- name: Wifi
- name: Café / thé à volonté
- name: Cuisine avec micro-onde, frigo, congèlateur
- name: Imprimante A4 avec utilisation modéré (si besoin d'imprimer, on te demandera d'apporter une ramette ou une cartouche)
- name: Casiers fermant avec un cadenas (non fourni)
- name: Cour extérieure parfaite pour une pause dej au soleil, prendre l'air, etc.
- name: Parking à vélo
